# Generated by Django 3.2.16 on 2023-09-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_telegramanalysis_conclusion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('device_type', models.CharField(max_length=100)),
                ('device_model', models.CharField(max_length=100)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('picture', models.ImageField(upload_to='recycle_pictures/')),
                ('pickup_type', models.CharField(max_length=50)),
                ('pickup_date', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='TelegramAnalysis',
        ),
    ]
