# Generated by Django 3.2.16 on 2023-09-21 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20230920_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='recycle',
            name='delivery_partner',
            field=models.CharField(default='Yashwant', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recycle',
            name='delivery_partner_phone',
            field=models.IntegerField(default=9600963451),
            preserve_default=False,
        ),
    ]
