# Generated by Django 3.2.16 on 2023-09-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_ewastelocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('device_type', models.CharField(blank=True, max_length=100, null=True)),
                ('device_model', models.CharField(max_length=100)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('picture', models.ImageField(upload_to='recycle_pictures/')),
                ('result', models.CharField(max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AnalysisResult',
        ),
    ]
