# Generated by Django 3.2.16 on 2023-09-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_resource_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recycle',
            name='delivery_partner',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recycle',
            name='delivery_partner_phone',
            field=models.IntegerField(null=True),
        ),
    ]
