# Generated by Django 3.2.16 on 2023-09-22 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_recycle_claim_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='recycle',
            name='requestid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
