# Generated by Django 3.2.16 on 2023-09-22 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_recycle_requestid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recycle',
            name='stage',
            field=models.IntegerField(null=True),
        ),
    ]
