# Generated by Django 3.2.16 on 2023-09-22 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_recycle_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recycle',
            name='claim_credit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recycle',
            name='delivery_partner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recycle',
            name='delivery_partner_phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recycle',
            name='requestid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recycle',
            name='stage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
